name: Lint Electron app

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "electron_app"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/-1
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - run: npm ci
      - name: Lint Electron app
        run: npm run lint
