name: Lint Electron app

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        working-directory: ./electron-app
        uses: actions/setup-node@v3
        with:
          node-version: lts
          cache: "npm"
      - run: npm ci
        working-directory: ./electron-app
      - name: Lint Electron app
        run: npm lint
        working-directory: ./electron-app
